-- Generated from fish_db.xlsx sheet: fishing_zones
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (1, '区域一：新手港湾', '刚买到人生第一杆钓竿的人常被推荐的钓点，只能钓到寻常鱼类。', 1000, 292, '{"rarity_distribution": [0.6, 0.3, 0.08, 0.02, 0, 0]}', 1, NULL, NULL, NULL, 0, 10);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (2, '区域二：入门海峡', '积累了一定钓获后就会被推荐来这里，据说偶尔能钓到不同寻常的鱼。', 15000, 325, '{"rarity_distribution": [0.4, 0.3, 0.2, 0.09, 0.01, 0]}', 1, NULL, NULL, 18, 1, 30);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (3, '区域三：鱼光临海域', '被鱼光临渔具有限公司控制的海域，需要从他们那购买通行证才可以进入。该死的资本。', 30000, 320, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.18, 0.069, 0.001]}', 1, NULL, NULL, 12, 1, 100);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (4, '区域四：鱼光临海域-VIP专属区域', '为VIP客户开放的特殊区域，资本的大手养殖着一些特殊的鱼类。钓起的鱼最终还是卖给了他们公司，你也分不清到底是你赚了还是他们赚了。', 50000, 920, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.18, 0.069, 0.001]}', 1, NULL, NULL, 13, 1, 300);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (5, '区域五：全自动工厂污染区域', '被久远的工业自动化群排除的污水污染得不成样的海域，工厂至今也还在全自动运作；有一些独特的鱼生活在这里。', 100000, 20, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.14, 0.1, 0.01]}', 1, NULL, NULL, 14, 1, 1000);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (6, '区域六：云雾缭绕的龙瀑之巅', '传说中鲤鱼化龙之地，此地位处极高，又冷又缺氧，但灵气充裕，修行之鱼会在此停留。', 100000, 102, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.14, 0.1, 0.01]}', 1, NULL, NULL, 15, 1, 1000);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (7, '区域七：莫可名状的深渊之底', '海域中凭空出现的神秘巨大漩涡，宁静得就像寻常海面一般。一些奇特的鱼会在此出没，也不知它们是否是遭到漩涡影响。', 100000, 81, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.14, 0.1, 0.01]}', 1, NULL, NULL, 16, 1, 1000);
INSERT INTO "fishing_zones" ("id", "name", "description", "daily_rare_fish_quota", "rare_fish_caught_today", "configs", "is_active", "available_from", "available_until", "required_item_id", "requires_pass", "fishing_cost") VALUES (8, '区域八：空气沸腾的龙之洞窟', '巨大的火山洞窟中，深不见底的地下水池，洞窟深处仿佛连空气都在沸腾翻滚，一些特殊的鱼出没于此地。', 100000, 581, '{"rarity_distribution": [0.25, 0.25, 0.25, 0.14, 0.1, 0.01]}', 1, NULL, NULL, 17, 1, 1000);
