-- Generated from fish_db.xlsx sheet: shops
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (1, '鱼满离·入门渔具铺', '欢迎光临！使用我们的渔具，鱼一定会满意地离开！', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-11-26 12:12:33', '2025-11-26 12:52:51');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (2, '鱼光临·海岸直营店', '欢迎光临鱼光临！啊当然，店名并不是在说客人您是鱼的意思！', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-11-26 12:16:58', '2025-11-26 14:12:50');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (3, '鱼甄选·特许回收部', '听说您钓起了非常特殊的鱼类，请务必让我方高价（大嘘）收购！', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-12-22 02:43:26', '2025-12-22 12:43:07');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (4, '鱼寻思·海洋研究院', '诚挚邀请您加入鱼类进化科研项目！当然，为了证明包括资金与周转能力在内的您的实力，只需要一笔小小的入项费……', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2026-01-08 15:57:25', '2026-04-14 17:41:17');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (5, '裂隙中的机械臂', '这支机械臂朝你招手，然后向你展示了各类全息影像。', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-11-26 12:34:08', '2025-12-08 06:38:31');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (6, '龙瀑洞天', '瀑布之中别有洞天，静候有缘人的奇遇之地。', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-11-26 12:37:50', '2025-12-08 06:38:24');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (7, '幻梦境', '你沉溺于虚幻缥缈又无比真实之梦。不可遗忘。不可悲叹。', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2025-11-26 12:49:05', '2025-12-08 06:38:36');
INSERT INTO "shops" ("shop_id", "name", "description", "shop_type", "is_active", "start_time", "end_time", "daily_start_time", "daily_end_time", "sort_order", "created_at", "updated_at") VALUES (8, '沉月海塔', '月亮在此坠入海底，化身为银白之高塔。', 'normal', 1, NULL, NULL, NULL, NULL, 100, '2026-05-02 00:00:00', '2026-05-02 00:00:00');
